### ISSUE TITLE
Run test.py error

### ISSUE THREAD

**Issue by tobymu** [IDEA-Research/DAB-DETR#52]
I use 8-node V100 and the environment is below:

Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.9.0+cu102'

Error info: cuda out of memory
> test.py
* True check_forward_equal_with_pytorch_double: max_abs_err 8.67e-19 max_rel_err 2.35e-16
* True check_forward_equal_with_pytorch_float: max_abs_err 4.66e-10 max_rel_err 1.13e-07
* True check_gradient_numerical(D=30)
* True check_gradient_numerical(D=32)
* True check_gradient_numerical(D=64)
* True check_gradient_numerical(D=71)
* True check_gradient_numerical(D=1025)
Traceback (most recent call last):
  File "test.py", line 86, in <module>
    check_gradient_numerical(channels, True, True, True)
  File "test.py", line 76, in check_gradient_numerical
    gradok = gradcheck(func, (value.double(), shapes, level_start_index, sampling_locations.double(), attention_weights.double(), im2col_step))
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1245, in gradcheck
    return _gradcheck_helper(**args)
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1258, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 930, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 974, in _slow_gradcheck
    analytical = _check_analytical_jacobian_attributes(tupled_inputs, o, nondet_tol, check_grad_dtypes)
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 520, in _check_analytical_jacobian_attributes
    jacobians1, types_ok, sizes_ok = _stack_and_check_tensors(vjps1, inputs, output_numel)
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 461, in _stack_and_check_tensors
    out_jacobians = _allocate_jacobians_with_inputs(inputs, numel_outputs)
  File "/root/anaconda3/envs/www_update/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 31, in _allocate_jacobians_with_inputs
    out.append(t.new_zeros((t.numel(), numel_output), layout=torch.strided))
RuntimeError: CUDA out of memory. Tried to allocate 7.50 GiB (GPU 0; 31.75 GiB total capacity; 22.52 GiB already allocated; 6.90 GiB free; 23.52 GiB reserved in total by PyTorch)

**Comment by SlongLiu** [comment]
it is strange to out of cuda mem with V100 during inference. I suggest you check if other processes runed on the same GPU device.

**Comment by iTruffle** [comment]
I get the same error on NVIDIA GeForce RTX 3090 and Quadro RTX 5000. I set the environment as python=3.7,pytorch=1.9.0,cuda=11.1.
And I can successfully run DETR and Deformable-DETR on the same environment.
I restart the environment, and I get this error again.
![image](https://user-images.githubusercontent.com/80766557/201309889-b5b087c2-f689-4beb-bb04-c3a9a49c565c.png)
![image](https://user-images.githubusercontent.com/80766557/201309966-52bd48ce-6bec-4b61-87a6-c04dcc542e18.png)

**Comment by iTruffle** [comment]
And I successfully run the evaluation code. 
This error can be ignored.
